### ISSUE TITLE
"Copy the Reference" Challenge stops marking incorrect colours on multi-colour sprites

### ISSUE THREAD

**Issue by ncraike** [Retronator/Pixel-Art-Academy#115]
I'm playing the "Learn Mode Demo 1.1.0" from Steam, and I _think_ I've hit a bug in one of the "Copy the Reference" challenges.

I asked for a multiple colour (not monochrome) sprite, and was given the walker from "Into The Breach". It's a tough one because there's some very similar shades of dark grey/green, but I also noticed at a certain point the canvas stops marking certain colours as incorrect.

Pixels which should be background (i.e. erased) are still marked with a small white square, and after using the fill/gradient tool to fill in the body with one shade of green, I _was_ definitely shown some colours as needing changing (e.g. the yellow-green/khaki colour). But as I got close to finishing the drawing, certain colours stopped being marked.

In the attached screenshot you can see the 2x2 square in the centre which _should_ be pink is not being marked incorrect, but a few squares below that there's an outline pixel which should be background/erased which _is_ indicated as incorrect.

![image](https://github.com/user-attachments/assets/4bcc5d28-695e-497a-9c1b-29dc60055a2f)

I did exit to the menus and then re-edit the drawing, so maybe that's complicated the issue. But I _think_ I was having the issue before that.

Also: sorry if this Git repo isn't the best place to file bugs in the demo from Steam. I got here by clicking the "Learn Mode Demo 1.1.0" text in the bottom-right of the game. Let me know if there's a better place to post bug reports!

**Comment by MatejJan** [comment]
It's OK, reporting here is fine. Another place is my [Discord](https://discord.gg/mngNfvTwG6) where this was reported before (if it is the same issue).

Quitting and re-entering a sprite definitely makes the hints not appear anymore. This has already been fixed in the release branch (but not in the demo). 

If it is indeed this bug, as a temporary workaround, you can put this into the game console (press alt to open the app menu > Debug > Toggle Developer Tools) as a temporary fix:
```
PAA.PixelPad.Apps.Drawing.Editor.getEditor().activeAsset().hintsEngineComponents.overlaid.drawMissingPixelsUpTo(null)
```

Does that re-enable the hints?

**Comment by ncraike** [comment]
That does seem to re-enable hints, yes. Thanks.

**Comment by MatejJan** [comment]
Good to know it's the same thing, thanks for reporting! I'll close it as fixed and I hope to have an updated demo build up next week too.
