### ISSUE TITLE
README/package.json missing dependency

### ISSUE THREAD

**Issue by Gaffen** [Retronator/Pixel-Art-Academy#30]
I just installed and compiled PAA, but noticed that on deploy I was missing two packages. Namely the following:

- babel-runtime
- bcrypt

Proposed solution:

Either add dependencies to package.json, or prompt user to globally install these packages with node

**Comment by MatejJan** [comment]
Thanks, this happened at some point of upgrading Meteor. There is a new way of linking NPM packages that I tried to upgrade to, but it then failed to find bcrypt on the server (there's a native implementation it couldn't find in the server's installed libs). I think the current version uses the js script one, but it's been a while since I was dealing with this, I could be way off.

Same for babel, it's due to Meteor upgrades.

Let's see if it's as simple as adding the dependencies to artificial package.

**Comment by Gaffen** [comment]
Damn, when you tested this, did you do a fresh install? I just deleted `node_modules` and reinstalled all deps... to find I was prompted to install `babel-runtime` again 😣

**Comment by Gaffen** [comment]
...However running `meteor npm install` from a fresh checkout of the repo followed by `meteor` appears to run the app fine.

Is there a reason to run `meteor update` rather than `meteor npm install`? If not I propose that the readme be updated to the two commands above.

**Comment by MatejJan** [comment]
Fixed in the readme, thanks!
